INSERT INTO RATING_MPA (id, name)
VALUES (1, 'G');
INSERT INTO RATING_MPA (id, name)
VALUES (2, 'PG');
INSERT INTO RATING_MPA (id, name)
VALUES (3, 'PG-13');
INSERT INTO RATING_MPA (id, name)
VALUES (4, 'R');
INSERT INTO RATING_MPA (id, name)
VALUES (5, 'NC-17');