DROP TABLE IF EXISTS genre_film ;
DROP TABLE IF EXISTS film;
DROP TABLE IF EXISTS rating_mpa;
DROP TABLE IF EXISTS friends;
DROP TABLE IF EXISTS USER_MAN;

CREATE TABLE IF NOT EXISTS genre_types (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name varchar NOT NULL,
    CONSTRAINT genre_types_pk PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS rating_mpa (
    id integer PRIMARY KEY,
    name varchar (255),
    CONSTRAINT unique_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS film (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL,
    description varchar,
    releaseDate date,
    duration integer,
    mpa varchar,
    CONSTRAINT mpa_fk FOREIGN KEY(mpa) REFERENCES rating_mpa(id)
);

DELETE FROM film;

CREATE TABLE IF NOT EXISTS  genre_film (
    id_film integer REFERENCES film(id),
    id_genre integer REFERENCES genre_types(id),
    CONSTRAINT genre_film_pk PRIMARY KEY(id_film, id_genre)
);

CREATE TABLE IF NOT EXISTS user_man (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login varchar,
    email varchar,
    name varchar,
    birthday date
);

DELETE FROM user_man;

CREATE TABLE IF NOT EXISTS friends (
    id_user integer NOT NULL,
    id_friend integer NOT NULL,
    friendship_status varchar,
    CONSTRAINT id_user_fk FOREIGN KEY(id_user) REFERENCES USER_MAN(id),
    CONSTRAINT id_friend_fk FOREIGN KEY(id_friend) REFERENCES USER_MAN(id)
);